In [71]:
# code from https://stackoverflow.com/questions/66896138/python-numpy-insert-2d-array-into-bigger-2d-array-on-given-posiiton user: Elmahy
import numpy as np

big = np.zeros((4, 4))

to_insert_arr = np.array([
    [1, 2],
    [3, 4]
])

def insert_at(big_arr, pos, to_insert_arr):
    x1 = pos[0]
    y1 = pos[1]
    x2 = x1 + to_insert_arr.shape[0]
    y2 = y1 + to_insert_arr.shape[1]

    assert x2  <= big.shape[0], "the position will make the small matrix exceed the boundaries at x"
    assert y2  <= big.shape[1], "the position will make the small matrix exceed the boundaries at y"

    big[x1:x2,y1:y2] = to_insert_arr

    return big
    


result = insert_at(big, (0, 0), to_insert_arr)
result

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
import numpy as np

In [73]:
def move_tetromino(board, pos, tetromino):
    """Inserts tetromino in copy of board at pos"""
    x1 = pos[0]
    y1 = pos[1]
    x2 = x1 + tetromino.shape[0]
    y2 = y1 + tetromino.shape[1]

    assert x2  <= board.shape[0], "the position will make the small matrix exceed the boundaries at x"
    assert y2  <= board.shape[1], "the position will make the small matrix exceed the boundaries at y"

    new_board = np.array(board) # needs to be array() to point to different location
    new_board[x1:x2,y1:y2] = tetromino

    return new_board # returns new board, TODO: update board = new board when tetromino is locked in place

In [74]:
board = np.zeros((20, 10))                      # board (10x20 ((20x10)))
square = np.ones((2, 2))                        # Square-shape
line = np.ones((4, 1))                          # Line-shape
T, T[1, 0], T[1, 2] = np.ones((2, 3)), 0, 0     # T-shape
L1, L1[0:2, 1] = np.ones((3, 2)), 0             # L-shape one
L2, L2[0:2, 0] = np.ones((3, 2)), 0             # L-shape two
Z1, Z1[0, 0], Z1[1, 2] = np.ones((2, 3)), 0, 0  # Z-shape one
Z2, Z2[1, 0], Z2[0, 2] = np.ones((2, 3)), 0, 0  # Z-shape two

position = (0, 4)

In [75]:
board = np.zeros((5, 10))

temp_board = move_tetromino(board, position, square)
print(temp_board, "\n")

temp_board = move_tetromino(board, position, line)
print(temp_board)

[[0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
